classDiagram
  class HealthScore
  class ReportData
  class GitInfo
  class DuplicateBlock
  class SecurityFinding
  class TodoItem
  class FileMetrics
  class FileInfo
  class Spinner
  class ProgressBar
  class ReportHandler
  http.server.SimpleHTTPRequestHandler <|-- ReportHandler
  class Name
  Parent <|-- Name
  class HealthScore
  class ReportData
  class GitInfo
  class DuplicateBlock
  class SecurityFinding
  class TodoItem
  class FileMetrics
  class FileInfo
  class ReportHandler
  http.server.SimpleHTTPRequestHandler <|-- ReportHandler
  class Spinner
  class ProgressBar
  class Name
  Parent <|-- Name
  class TestBaseline
  unittest.TestCase <|-- TestBaseline
  class FakeFile
  class TestCLI
  unittest.TestCase <|-- TestCLI
  class TestDuplicates
  unittest.TestCase <|-- TestDuplicates
  class TestGit
  unittest.TestCase <|-- TestGit
  class TestLanguages
  unittest.TestCase <|-- TestLanguages
  class TestMetrics
  unittest.TestCase <|-- TestMetrics
  class A
  class TestPackagingEntrypoint
  unittest.TestCase <|-- TestPackagingEntrypoint
  class TestZeroRuntimeDependencies
  unittest.TestCase <|-- TestZeroRuntimeDependencies
  class TestParallelScanning
  unittest.TestCase <|-- TestParallelScanning
  class TestScanner
  unittest.TestCase <|-- TestScanner
  class TestScoring
  unittest.TestCase <|-- TestScoring
  class TestSecurity
  unittest.TestCase <|-- TestSecurity
  class TestStructure
  unittest.TestCase <|-- TestStructure
  class TestTodos
  unittest.TestCase <|-- TestTodos