"""
Unit tests for build_single_file.py
Generated by RepoDoctor
"""

import unittest

from build_single_file import build


class TestFunctions(unittest.TestCase):
    """Test functions from the module."""

    def test_build(self):
        """Test build function."""
        # TODO: Implement test for build
        result = build()
        self.assertIsNotNone(result)



if __name__ == "__main__":
    unittest.main()
