"""
Unit tests for models.py
Generated by RepoDoctor
"""

import unittest

from repodoctor.models import HealthScore, ReportData, GitInfo, DuplicateBlock, SecurityFinding


class TestHealthScore(unittest.TestCase):
    """Test HealthScore class."""

    def setUp(self):
        """Set up test fixtures for HealthScore."""
        self.instance = HealthScore()

    def test_instantiation(self):
        """Test that HealthScore can be instantiated."""
        self.assertIsNotNone(self.instance)

    def test_type(self):
        """Test that instance is of correct type."""
        self.assertIsInstance(self.instance, HealthScore)


class TestReportData(unittest.TestCase):
    """Test ReportData class."""

    def setUp(self):
        """Set up test fixtures for ReportData."""
        self.instance = ReportData()

    def test_instantiation(self):
        """Test that ReportData can be instantiated."""
        self.assertIsNotNone(self.instance)

    def test_type(self):
        """Test that instance is of correct type."""
        self.assertIsInstance(self.instance, ReportData)


class TestGitInfo(unittest.TestCase):
    """Test GitInfo class."""

    def setUp(self):
        """Set up test fixtures for GitInfo."""
        self.instance = GitInfo()

    def test_instantiation(self):
        """Test that GitInfo can be instantiated."""
        self.assertIsNotNone(self.instance)

    def test_type(self):
        """Test that instance is of correct type."""
        self.assertIsInstance(self.instance, GitInfo)


class TestDuplicateBlock(unittest.TestCase):
    """Test DuplicateBlock class."""

    def setUp(self):
        """Set up test fixtures for DuplicateBlock."""
        self.instance = DuplicateBlock()

    def test_instantiation(self):
        """Test that DuplicateBlock can be instantiated."""
        self.assertIsNotNone(self.instance)

    def test_type(self):
        """Test that instance is of correct type."""
        self.assertIsInstance(self.instance, DuplicateBlock)


class TestSecurityFinding(unittest.TestCase):
    """Test SecurityFinding class."""

    def setUp(self):
        """Set up test fixtures for SecurityFinding."""
        self.instance = SecurityFinding()

    def test_instantiation(self):
        """Test that SecurityFinding can be instantiated."""
        self.assertIsNotNone(self.instance)

    def test_type(self):
        """Test that instance is of correct type."""
        self.assertIsInstance(self.instance, SecurityFinding)


class TestTodoItem(unittest.TestCase):
    """Test TodoItem class."""

    def setUp(self):
        """Set up test fixtures for TodoItem."""
        self.instance = TodoItem()

    def test_instantiation(self):
        """Test that TodoItem can be instantiated."""
        self.assertIsNotNone(self.instance)

    def test_type(self):
        """Test that instance is of correct type."""
        self.assertIsInstance(self.instance, TodoItem)


class TestFileMetrics(unittest.TestCase):
    """Test FileMetrics class."""

    def setUp(self):
        """Set up test fixtures for FileMetrics."""
        self.instance = FileMetrics()

    def test_instantiation(self):
        """Test that FileMetrics can be instantiated."""
        self.assertIsNotNone(self.instance)

    def test_type(self):
        """Test that instance is of correct type."""
        self.assertIsInstance(self.instance, FileMetrics)


class TestFileInfo(unittest.TestCase):
    """Test FileInfo class."""

    def setUp(self):
        """Set up test fixtures for FileInfo."""
        self.instance = FileInfo()

    def test_instantiation(self):
        """Test that FileInfo can be instantiated."""
        self.assertIsNotNone(self.instance)

    def test_type(self):
        """Test that instance is of correct type."""
        self.assertIsInstance(self.instance, FileInfo)



if __name__ == "__main__":
    unittest.main()
